# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module AggregationFunc
      COUNT = 'count'
      COUNT_DISTINCT = 'count-distinct'
      HISTOGRAM = 'histogram'
      SUM = 'sum'
      MIN = 'min'
      MAX = 'max'
      AVG = 'avg'
      MEDIAN = 'median'
      P50 = 'p50'
      P90 = 'p90'
      P95 = 'p95'
      P99 = 'p99'

      def self.all
        @all ||= [
          COUNT,
          COUNT_DISTINCT,
          HISTOGRAM,
          SUM,
          MIN,
          MAX,
          AVG,
          MEDIAN,
          P50,
          P90,
          P95,
          P99,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
