# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class AlertEdge
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :edge_type,
        type: 'EdgeType',
        json_key: 'edge_type',
        required: true

      attribute :from_node_index,
        type: 'Integer',
        json_key: 'from_node_index',
        required: true,
        minimum: 0

      attribute :to_node_index,
        type: 'Integer',
        json_key: 'to_node_index',
        required: true,
        minimum: 0

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
