# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module AlertTypeFilter
      ALL = 'all'
      SCHEDULED = 'scheduled'
      REALTIME = 'realtime'
      ANOMALY_DETECTION = 'anomaly_detection'

      def self.all
        @all ||= [
          ALL,
          SCHEDULED,
          REALTIME,
          ANOMALY_DETECTION,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
