# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class AssumeServiceAccountRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :duration_seconds,
        type: 'Integer',
        json_key: 'duration_seconds',
        required: false,
        minimum: 0

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: true

      attribute :service_account,
        type: 'String',
        json_key: 'service_account',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
