# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class AssumeServiceAccountResponse
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :expires_at,
        type: 'String',
        json_key: 'expires_at',
        required: true

      attribute :expires_in,
        type: 'Integer',
        json_key: 'expires_in',
        required: true,
        minimum: 0

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: true

      attribute :role_name,
        type: 'String',
        json_key: 'role_name',
        required: true

      attribute :session_id,
        type: 'String',
        json_key: 'session_id',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
