# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class AxisItem
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :alias_,
        type: 'String',
        json_key: 'alias',
        required: true

      attribute :args,
        type: 'Array<AxisArg>',
        json_key: 'args',
        required: false

      attribute :color,
        type: 'String',
        json_key: 'color',
        required: false

      attribute :column,
        type: 'String',
        json_key: 'column',
        required: false

      attribute :function_name,
        type: 'String',
        json_key: 'functionName',
        required: false

      attribute :having_conditions,
        type: 'Array<HavingConditions>',
        json_key: 'havingConditions',
        required: false

      attribute :is_derived,
        type: 'Boolean',
        json_key: 'isDerived',
        required: false

      attribute :label,
        type: 'String',
        json_key: 'label',
        required: true

      attribute :raw_query,
        type: 'String',
        json_key: 'rawQuery',
        required: false

      attribute :show_field_as_json,
        type: 'Boolean',
        json_key: 'showFieldAsJson',
        required: false

      attribute :sort_by,
        type: 'String',
        json_key: 'sortBy',
        required: false

      attribute :treat_as_non_timestamp,
        type: 'Boolean',
        json_key: 'treatAsNonTimestamp',
        required: false

      attribute :type,
        type: 'AxisType',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
