# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class BackfillRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :chunk_period_minutes,
        type: 'Integer',
        json_key: 'chunk_period_minutes',
        required: false

      attribute :delay_between_chunks_secs,
        type: 'Integer',
        json_key: 'delay_between_chunks_secs',
        required: false

      attribute :delete_before_backfill,
        type: 'Boolean',
        json_key: 'delete_before_backfill',
        required: false

      attribute :end_time,
        type: 'Integer',
        json_key: 'end_time',
        required: true

      attribute :start_time,
        type: 'Integer',
        json_key: 'start_time',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
