# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class BackfillJobStatus
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :chunk_period_minutes,
        type: 'Integer',
        json_key: 'chunk_period_minutes',
        required: false

      attribute :chunks_completed,
        type: 'Integer',
        json_key: 'chunks_completed',
        required: false,
        minimum: 0

      attribute :chunks_total,
        type: 'Integer',
        json_key: 'chunks_total',
        required: false,
        minimum: 0

      attribute :created_at,
        type: 'Integer',
        json_key: 'created_at',
        required: false

      attribute :current_position,
        type: 'Integer',
        json_key: 'current_position',
        required: true

      attribute :delay_between_chunks_secs,
        type: 'Integer',
        json_key: 'delay_between_chunks_secs',
        required: false

      attribute :delete_before_backfill,
        type: 'Boolean',
        json_key: 'delete_before_backfill',
        required: false

      attribute :deletion_job_ids,
        type: 'Array<String>',
        json_key: 'deletion_job_ids',
        required: false

      attribute :deletion_status,
        type: 'DeletionStatus',
        json_key: 'deletion_status',
        required: false

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: true

      attribute :end_time,
        type: 'Integer',
        json_key: 'end_time',
        required: true

      attribute :error,
        type: 'String',
        json_key: 'error',
        required: false

      attribute :job_id,
        type: 'String',
        json_key: 'job_id',
        required: true

      attribute :last_triggered_at,
        type: 'Integer',
        json_key: 'last_triggered_at',
        required: false

      attribute :pipeline_id,
        type: 'String',
        json_key: 'pipeline_id',
        required: true

      attribute :pipeline_name,
        type: 'String',
        json_key: 'pipeline_name',
        required: false

      attribute :progress_percent,
        type: 'Integer',
        json_key: 'progress_percent',
        required: true,
        minimum: 0

      attribute :start_time,
        type: 'Integer',
        json_key: 'start_time',
        required: true

      attribute :status,
        type: 'String',
        json_key: 'status',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
