# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class BulkResponseError
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :index,
        type: 'String',
        json_key: 'index',
        required: true

      attribute :index_uuid,
        type: 'String',
        json_key: 'index_uuid',
        required: true

      attribute :reason,
        type: 'String',
        json_key: 'reason',
        required: true

      attribute :shard,
        type: 'String',
        json_key: 'shard',
        required: true

      attribute :type,
        type: 'String',
        json_key: 'type',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
