# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class BulkResponseItem
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :_id,
        type: 'String',
        json_key: '_id',
        required: true

      attribute :_index,
        type: 'String',
        json_key: '_index',
        required: true

      attribute :_primary_term,
        type: 'Integer',
        json_key: '_primary_term',
        required: false

      attribute :_seq_no,
        type: 'Integer',
        json_key: '_seq_no',
        required: false

      attribute :_shards,
        type: 'ShardResponse',
        json_key: '_shards',
        required: false

      attribute :_version,
        type: 'Integer',
        json_key: '_version',
        required: false

      attribute :error,
        type: 'BulkResponseError',
        json_key: 'error',
        required: false

      attribute :original_record,
        type: 'Object',
        json_key: 'originalRecord',
        required: false

      attribute :result,
        type: 'String',
        json_key: 'result',
        required: false

      attribute :status,
        type: 'Integer',
        json_key: 'status',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
