# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class BulkResponse
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :errors,
        type: 'Boolean',
        json_key: 'errors',
        required: true

      attribute :items,
        type: 'Array<Hash<String, BulkResponseItem>>',
        json_key: 'items',
        required: true

      attribute :took,
        type: 'Integer',
        json_key: 'took',
        required: true,
        minimum: 0

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
