# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module CardinalityClass
      VERY_LOW = 'VeryLow'
      LOW = 'Low'
      MEDIUM = 'Medium'
      HIGH = 'High'
      VERY_HIGH = 'VeryHigh'

      def self.all
        @all ||= [
          VERY_LOW,
          LOW,
          MEDIUM,
          HIGH,
          VERY_HIGH,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
