# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ColorCfg
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :color_by_series,
        type: 'Array<ColorBySeries>',
        json_key: 'colorBySeries',
        required: false

      attribute :fixed_color,
        type: 'Array<String>',
        json_key: 'fixedColor',
        required: false

      attribute :mode,
        type: 'String',
        json_key: 'mode',
        required: false

      attribute :series_by,
        type: 'String',
        json_key: 'seriesBy',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
