# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ConfigOneOf1
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :auto_color,
        type: 'Boolean',
        json_key: 'autoColor',
        required: false

      attribute :type,
        type: 'String',
        json_key: 'type',
        required: true,
        enum: ['unique_value_color']

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
