# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class CorrelationRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :available_dimensions,
        type: 'Hash<String, String>',
        json_key: 'available_dimensions',
        required: true

      attribute :source_stream,
        type: 'String',
        json_key: 'source_stream',
        required: true

      attribute :source_type,
        type: 'String',
        json_key: 'source_type',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
