# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class CorrelationResponse
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :additional_dimensions,
        type: 'Hash<String, String>',
        json_key: 'additional_dimensions',
        required: true

      attribute :all_streams,
        type: 'Array<StreamInfo>',
        json_key: 'all_streams',
        required: false

      attribute :matched_dimensions,
        type: 'Hash<String, String>',
        json_key: 'matched_dimensions',
        required: true

      attribute :matched_set_id,
        type: 'String',
        json_key: 'matched_set_id',
        required: false

      attribute :related_streams,
        type: 'RelatedStreams',
        json_key: 'related_streams',
        required: true

      attribute :service_name,
        type: 'String',
        json_key: 'service_name',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
