# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module CorrelationReason
      SERVICE_DISCOVERY = 'service_discovery'
      PRIMARY_MATCH = 'primary_match'
      SECONDARY_MATCH = 'secondary_match'
      ALERT_ID = 'alert_id'

      def self.all
        @all ||= [
          SERVICE_DISCOVERY,
          PRIMARY_MATCH,
          SECONDARY_MATCH,
          ALERT_ID,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
