# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Dashboard
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :created,
        type: 'Time',
        json_key: 'created',
        required: false

      attribute :dashboard_id,
        type: 'String',
        json_key: 'dashboardId',
        required: false

      attribute :default_datetime_duration,
        type: 'DateTimeOptions',
        json_key: 'defaultDatetimeDuration',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: true

      attribute :owner,
        type: 'String',
        json_key: 'owner',
        required: false

      attribute :role,
        type: 'String',
        json_key: 'role',
        required: false

      attribute :tabs,
        type: 'Array<Tab>',
        json_key: 'tabs',
        required: false

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: true

      attribute :variables,
        type: 'Variables',
        json_key: 'variables',
        required: false

      attribute :version,
        type: 'Integer',
        json_key: 'version',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
