# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class DateTimeOptions
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :end_time,
        type: 'Integer',
        json_key: 'endTime',
        required: false

      attribute :relative_time_period,
        type: 'String',
        json_key: 'relativeTimePeriod',
        required: false

      attribute :start_time,
        type: 'Integer',
        json_key: 'startTime',
        required: false

      attribute :type,
        type: 'String',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
