# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class DedupSummaryResponse
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :alerts_with_dedup,
        type: 'Integer',
        json_key: 'alerts_with_dedup',
        required: true,
        minimum: 0

      attribute :passed_total,
        type: 'Integer',
        json_key: 'passed_total',
        required: true

      attribute :pending_batches,
        type: 'Integer',
        json_key: 'pending_batches',
        required: true

      attribute :suppression_rate,
        type: 'Float',
        json_key: 'suppression_rate',
        required: true

      attribute :suppressions_total,
        type: 'Integer',
        json_key: 'suppressions_total',
        required: true

      attribute :timestamp,
        type: 'Integer',
        json_key: 'timestamp',
        required: true

      attribute :total_alerts,
        type: 'Integer',
        json_key: 'total_alerts',
        required: true,
        minimum: 0

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
