# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class DeduplicationConfig
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: false

      attribute :fingerprint_fields,
        type: 'Array<String>',
        json_key: 'fingerprint_fields',
        required: false

      attribute :grouping,
        type: 'GroupingConfig',
        json_key: 'grouping',
        required: false

      attribute :time_window_minutes,
        type: 'Integer',
        json_key: 'time_window_minutes',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
