# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module DeletionStatus
      NOT_REQUIRED = 'not_required'
      PENDING = 'pending'
      IN_PROGRESS = 'in_progress'
      COMPLETED = 'completed'

      def self.all
        @all ||= [
          NOT_REQUIRED,
          PENDING,
          IN_PROGRESS,
          COMPLETED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
