# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class DimensionAnalytics
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :cardinality,
        type: 'Integer',
        json_key: 'cardinality',
        required: true,
        minimum: 0

      attribute :cardinality_class,
        type: 'CardinalityClass',
        json_key: 'cardinality_class',
        required: true

      attribute :dimension_name,
        type: 'String',
        json_key: 'dimension_name',
        required: true

      attribute :first_seen,
        type: 'Integer',
        json_key: 'first_seen',
        required: true

      attribute :last_updated,
        type: 'Integer',
        json_key: 'last_updated',
        required: true

      attribute :sample_values,
        type: 'Hash<String, Hash<String, Array<String>>>',
        json_key: 'sample_values',
        required: false

      attribute :service_count,
        type: 'Integer',
        json_key: 'service_count',
        required: true,
        minimum: 0

      attribute :value_children,
        type: 'Hash<String, Hash<String, Array<String>>>',
        json_key: 'value_children',
        required: false

      attribute :value_counts,
        type: 'Hash<String, Integer>',
        json_key: 'value_counts',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
