# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class DimensionAnalyticsSummary
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :available_groups,
        type: 'Array<FoundGroup>',
        json_key: 'available_groups',
        required: false

      attribute :by_cardinality,
        type: 'Hash<String, Array<String>>',
        json_key: 'by_cardinality',
        required: true

      attribute :dimensions,
        type: 'Array<DimensionAnalytics>',
        json_key: 'dimensions',
        required: true

      attribute :generated_at,
        type: 'Integer',
        json_key: 'generated_at',
        required: true

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: true

      attribute :recommended_priority_dimensions,
        type: 'Array<String>',
        json_key: 'recommended_priority_dimensions',
        required: true

      attribute :service_field_sources,
        type: 'Array<ServiceFieldSource>',
        json_key: 'service_field_sources',
        required: false

      attribute :total_dimensions,
        type: 'Integer',
        json_key: 'total_dimensions',
        required: true,
        minimum: 0

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
