# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class DrillDown
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :data,
        type: 'DrillDownData',
        json_key: 'data',
        required: false

      attribute :find_by,
        type: 'String',
        json_key: 'findBy',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :target_blank,
        type: 'Boolean',
        json_key: 'targetBlank',
        required: false

      attribute :type,
        type: 'String',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
