# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class DrillDownData
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :dashboard,
        type: 'String',
        json_key: 'dashboard',
        required: false

      attribute :folder,
        type: 'String',
        json_key: 'folder',
        required: false

      attribute :logs_mode,
        type: 'String',
        json_key: 'logsMode',
        required: false

      attribute :logs_query,
        type: 'String',
        json_key: 'logsQuery',
        required: false

      attribute :pass_all_variables,
        type: 'Boolean',
        json_key: 'passAllVariables',
        required: false

      attribute :tab,
        type: 'String',
        json_key: 'tab',
        required: false

      attribute :url,
        type: 'String',
        json_key: 'url',
        required: false

      attribute :variables,
        type: 'Array<DrillDownVariables>',
        json_key: 'variables',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
