# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module EnrichmentTableStatus
      PENDING = 'pending'
      PROCESSING = 'processing'
      COMPLETED = 'completed'
      FAILED = 'failed'

      def self.all
        @all ||= [
          PENDING,
          PROCESSING,
          COMPLETED,
          FAILED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
