# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class EnrichmentTableUrlJob
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :append_data,
        type: 'Boolean',
        json_key: 'append_data',
        required: true

      attribute :created_at,
        type: 'Integer',
        json_key: 'created_at',
        required: true

      attribute :error_message,
        type: 'String',
        json_key: 'error_message',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: true

      attribute :last_byte_position,
        type: 'Integer',
        json_key: 'last_byte_position',
        required: true,
        minimum: 0

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: true

      attribute :retry_count,
        type: 'Integer',
        json_key: 'retry_count',
        required: true,
        minimum: 0

      attribute :status,
        type: 'EnrichmentTableStatus',
        json_key: 'status',
        required: true

      attribute :supports_range,
        type: 'Boolean',
        json_key: 'supports_range',
        required: true

      attribute :table_name,
        type: 'String',
        json_key: 'table_name',
        required: true

      attribute :total_bytes_fetched,
        type: 'Integer',
        json_key: 'total_bytes_fetched',
        required: true,
        minimum: 0

      attribute :total_records_processed,
        type: 'Integer',
        json_key: 'total_records_processed',
        required: true

      attribute :updated_at,
        type: 'Integer',
        json_key: 'updated_at',
        required: true

      attribute :url,
        type: 'String',
        json_key: 'url',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
