# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class FieldAlias
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :display,
        type: 'String',
        json_key: 'display',
        required: true

      attribute :fields,
        type: 'Array<String>',
        json_key: 'fields',
        required: true

      attribute :group,
        type: 'String',
        json_key: 'group',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: true

      attribute :is_workload_type,
        type: 'Boolean',
        json_key: 'is_workload_type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
