# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class FilterCondition
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :column,
        type: 'StreamFieldObj',
        json_key: 'column',
        required: false

      attribute :filter_type,
        type: 'String',
        json_key: 'filterType',
        required: true

      attribute :logical_operator,
        type: 'String',
        json_key: 'logicalOperator',
        required: true

      attribute :operator,
        type: 'String',
        json_key: 'operator',
        required: false

      attribute :type,
        type: 'String',
        json_key: 'type',
        required: true

      attribute :value,
        type: 'String',
        json_key: 'value',
        required: false

      attribute :values,
        type: 'Array<String>',
        json_key: 'values',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
