# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class FoundGroup
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :aliases,
        type: 'Hash<String, String>',
        json_key: 'aliases',
        required: true

      attribute :cardinality_class,
        type: 'CardinalityClass',
        json_key: 'cardinality_class',
        required: false

      attribute :display,
        type: 'String',
        json_key: 'display',
        required: true

      attribute :group,
        type: 'String',
        json_key: 'group',
        required: false

      attribute :group_id,
        type: 'String',
        json_key: 'group_id',
        required: true

      attribute :recommended,
        type: 'Boolean',
        json_key: 'recommended',
        required: true

      attribute :stream_types,
        type: 'Array<String>',
        json_key: 'stream_types',
        required: true

      attribute :unique_values,
        type: 'Integer',
        json_key: 'unique_values',
        required: false,
        minimum: 0

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
