# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module FrequencyType
      CRON = 'cron'
      MINUTES = 'minutes'

      def self.all
        @all ||= [
          CRON,
          MINUTES,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
