# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class GetAlertResponseBody
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :context_attributes,
        type: 'Hash<String, String>',
        json_key: 'context_attributes',
        required: false

      attribute :creates_incident,
        type: 'Boolean',
        json_key: 'creates_incident',
        required: false

      attribute :deduplication,
        type: 'DeduplicationConfig',
        json_key: 'deduplication',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :destinations,
        type: 'Array<String>',
        json_key: 'destinations',
        required: false

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :is_real_time,
        type: 'Boolean',
        json_key: 'is_real_time',
        required: false

      attribute :last_edited_by,
        type: 'String',
        json_key: 'last_edited_by',
        required: false

      attribute :last_satisfied_at,
        type: 'Integer',
        json_key: 'last_satisfied_at',
        required: false

      attribute :last_triggered_at,
        type: 'Integer',
        json_key: 'last_triggered_at',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: false

      attribute :owner,
        type: 'String',
        json_key: 'owner',
        required: false

      attribute :query_condition,
        type: 'QueryCondition',
        json_key: 'query_condition',
        required: false

      attribute :row_template,
        type: 'String',
        json_key: 'row_template',
        required: false

      attribute :row_template_type,
        type: 'RowTemplateType',
        json_key: 'row_template_type',
        required: false

      attribute :stream_name,
        type: 'String',
        json_key: 'stream_name',
        required: false

      attribute :stream_type,
        type: 'StreamType',
        json_key: 'stream_type',
        required: false

      attribute :template,
        type: 'String',
        json_key: 'template',
        required: false

      attribute :trigger_condition,
        type: 'TriggerCondition',
        json_key: 'trigger_condition',
        required: false

      attribute :tz_offset,
        type: 'Integer',
        json_key: 'tz_offset',
        required: false

      attribute :updated_at,
        type: 'Time',
        json_key: 'updated_at',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
