# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class GetAlertHistory200Response
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :from,
        type: 'Integer',
        json_key: 'from',
        required: true

      attribute :hits,
        type: 'Array<AlertHistoryEntry>',
        json_key: 'hits',
        required: true

      attribute :size,
        type: 'Integer',
        json_key: 'size',
        required: true

      attribute :total,
        type: 'Integer',
        json_key: 'total',
        required: true,
        minimum: 0

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
