# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class GlobalDeduplicationConfig
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :alert_dedup_enabled,
        type: 'Boolean',
        json_key: 'alert_dedup_enabled',
        required: false

      attribute :alert_fingerprint_groups,
        type: 'Array<String>',
        json_key: 'alert_fingerprint_groups',
        required: false

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: false

      attribute :time_window_minutes,
        type: 'Integer',
        json_key: 'time_window_minutes',
        required: false

      attribute :upgrade_window_minutes,
        type: 'Integer',
        json_key: 'upgrade_window_minutes',
        required: false,
        minimum: 0

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
