# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class GroupingConfig
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: false

      attribute :group_wait_seconds,
        type: 'Integer',
        json_key: 'group_wait_seconds',
        required: false

      attribute :max_group_size,
        type: 'Integer',
        json_key: 'max_group_size',
        required: false,
        minimum: 0

      attribute :send_strategy,
        type: 'SendStrategy',
        json_key: 'send_strategy',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
