# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class HttpResponse
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :code,
        type: 'Integer',
        json_key: 'code',
        required: true,
        minimum: 0

      attribute :error_detail,
        type: 'String',
        json_key: 'error_detail',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :message,
        type: 'String',
        json_key: 'message',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :trace_id,
        type: 'String',
        json_key: 'trace_id',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
