# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module IncidentSeverity
      P1 = 'P1'
      P2 = 'P2'
      P3 = 'P3'
      P4 = 'P4'

      def self.all
        @all ||= [
          P1,
          P2,
          P3,
          P4,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
