# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class IncidentStats
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :acknowledged_incidents,
        type: 'Integer',
        json_key: 'acknowledged_incidents',
        required: true

      attribute :alerts_per_incident_avg,
        type: 'Float',
        json_key: 'alerts_per_incident_avg',
        required: true

      attribute :by_service,
        type: 'Hash<String, Integer>',
        json_key: 'by_service',
        required: true

      attribute :by_severity,
        type: 'Hash<String, Integer>',
        json_key: 'by_severity',
        required: true

      attribute :mttr_minutes,
        type: 'Float',
        json_key: 'mttr_minutes',
        required: false

      attribute :open_incidents,
        type: 'Integer',
        json_key: 'open_incidents',
        required: true

      attribute :resolved_incidents,
        type: 'Integer',
        json_key: 'resolved_incidents',
        required: true

      attribute :total_incidents,
        type: 'Integer',
        json_key: 'total_incidents',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
