# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class IncidentTopology
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :edges,
        type: 'Array<AlertEdge>',
        json_key: 'edges',
        required: true

      attribute :nodes,
        type: 'Array<AlertNode>',
        json_key: 'nodes',
        required: true

      attribute :related_incident_ids,
        type: 'Array<String>',
        json_key: 'related_incident_ids',
        required: true

      attribute :suggested_root_cause,
        type: 'String',
        json_key: 'suggested_root_cause',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
