# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class IncidentAlert
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :alert_fired_at,
        type: 'Integer',
        json_key: 'alert_fired_at',
        required: true

      attribute :alert_id,
        type: 'String',
        json_key: 'alert_id',
        required: true

      attribute :alert_name,
        type: 'String',
        json_key: 'alert_name',
        required: true

      attribute :correlation_reason,
        type: 'CorrelationReason',
        json_key: 'correlation_reason',
        required: true

      attribute :created_at,
        type: 'Integer',
        json_key: 'created_at',
        required: true

      attribute :incident_id,
        type: 'String',
        json_key: 'incident_id',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
