# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Incident
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :alert_count,
        type: 'Integer',
        json_key: 'alert_count',
        required: true

      attribute :assigned_to,
        type: 'String',
        json_key: 'assigned_to',
        required: false

      attribute :created_at,
        type: 'Integer',
        json_key: 'created_at',
        required: true

      attribute :first_alert_at,
        type: 'Integer',
        json_key: 'first_alert_at',
        required: true

      attribute :group_values,
        type: 'Object',
        json_key: 'group_values',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: true

      attribute :key_type,
        type: 'KeyType',
        json_key: 'key_type',
        required: false

      attribute :last_alert_at,
        type: 'Integer',
        json_key: 'last_alert_at',
        required: true

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: true

      attribute :resolved_at,
        type: 'Integer',
        json_key: 'resolved_at',
        required: false

      attribute :severity,
        type: 'IncidentSeverity',
        json_key: 'severity',
        required: true

      attribute :status,
        type: 'IncidentStatus',
        json_key: 'status',
        required: true

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: false

      attribute :topology_context,
        type: 'IncidentTopology',
        json_key: 'topology_context',
        required: false

      attribute :updated_at,
        type: 'Integer',
        json_key: 'updated_at',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
