# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class JoinCondition
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :left_field,
        type: 'SelectedField',
        json_key: 'leftField',
        required: true

      attribute :operation,
        type: 'String',
        json_key: 'operation',
        required: true

      attribute :right_field,
        type: 'SelectedField',
        json_key: 'rightField',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
