# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Join
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :conditions,
        type: 'Array<JoinCondition>',
        json_key: 'conditions',
        required: true

      attribute :join_type,
        type: 'String',
        json_key: 'joinType',
        required: true

      attribute :stream,
        type: 'String',
        json_key: 'stream',
        required: true

      attribute :stream_alias,
        type: 'String',
        json_key: 'streamAlias',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
