# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module LabelPosition
      TOP = 'top'
      LEFT = 'left'
      RIGHT = 'right'
      BOTTOM = 'bottom'
      INSIDE = 'inside'
      INSIDE_LEFT = 'insideLeft'
      INSIDE_RIGHT = 'insideRight'
      INSIDE_TOP = 'insideTop'
      INSIDE_BOTTOM = 'insideBottom'
      INSIDE_TOP_LEFT = 'insideTopLeft'
      INSIDE_BOTTOM_LEFT = 'insideBottomLeft'
      INSIDE_TOP_RIGHT = 'insideTopRight'
      INSIDE_BOTTOM_RIGHT = 'insideBottomRight'
      OUTSIDE = 'outside'

      def self.all
        @all ||= [
          TOP,
          LEFT,
          RIGHT,
          BOTTOM,
          INSIDE,
          INSIDE_LEFT,
          INSIDE_RIGHT,
          INSIDE_TOP,
          INSIDE_BOTTOM,
          INSIDE_TOP_LEFT,
          INSIDE_BOTTOM_LEFT,
          INSIDE_TOP_RIGHT,
          INSIDE_BOTTOM_RIGHT,
          OUTSIDE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
