# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Layout
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :h,
        type: 'Integer',
        json_key: 'h',
        required: false

      attribute :i,
        type: 'Integer',
        json_key: 'i',
        required: false

      attribute :w,
        type: 'Integer',
        json_key: 'w',
        required: false

      attribute :x,
        type: 'Integer',
        json_key: 'x',
        required: false

      attribute :y,
        type: 'Integer',
        json_key: 'y',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
