# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module LineInterpolation
      SMOOTH = 'smooth'
      LINEAR = 'linear'
      STEP_START = 'step-start'
      STEP_END = 'step-end'
      STEP_MIDDLE = 'step-middle'

      def self.all
        @all ||= [
          SMOOTH,
          LINEAR,
          STEP_START,
          STEP_END,
          STEP_MIDDLE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
