# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ListReportsV2200ResponseInner
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :created_at,
        type: 'Time',
        json_key: 'createdAt',
        required: false

      attribute :dashboards,
        type: 'Array<ReportDashboard>',
        json_key: 'dashboards',
        required: true

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :destinations,
        type: 'Array<ReportDestination>',
        json_key: 'destinations',
        required: true

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: false

      attribute :frequency,
        type: 'ReportFrequency',
        json_key: 'frequency',
        required: false

      attribute :image_preview,
        type: 'Boolean',
        json_key: 'imagePreview',
        required: false

      attribute :last_edited_by,
        type: 'String',
        json_key: 'lastEditedBy',
        required: false

      attribute :message,
        type: 'String',
        json_key: 'message',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :org_id,
        type: 'String',
        json_key: 'orgId',
        required: true

      attribute :owner,
        type: 'String',
        json_key: 'owner',
        required: false

      attribute :start,
        type: 'Integer',
        json_key: 'start',
        required: false

      attribute :timezone,
        type: 'String',
        json_key: 'timezone',
        required: false

      attribute :timezone_offset,
        type: 'Integer',
        json_key: 'timezoneOffset',
        required: false

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: false

      attribute :updated_at,
        type: 'Time',
        json_key: 'updatedAt',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
