# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ListAlertsResponseBodyItem
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :alert_id,
        type: 'String',
        json_key: 'alert_id',
        required: true

      attribute :alert_type,
        type: 'String',
        json_key: 'alert_type',
        required: true

      attribute :condition,
        type: 'QueryCondition',
        json_key: 'condition',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: true

      attribute :folder_id,
        type: 'String',
        json_key: 'folder_id',
        required: true

      attribute :folder_name,
        type: 'String',
        json_key: 'folder_name',
        required: true

      attribute :is_real_time,
        type: 'Boolean',
        json_key: 'is_real_time',
        required: true

      attribute :last_error,
        type: 'String',
        json_key: 'last_error',
        required: false

      attribute :last_satisfied_at,
        type: 'Integer',
        json_key: 'last_satisfied_at',
        required: false

      attribute :last_trained_at,
        type: 'Integer',
        json_key: 'last_trained_at',
        required: false

      attribute :last_triggered_at,
        type: 'Integer',
        json_key: 'last_triggered_at',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :owner,
        type: 'String',
        json_key: 'owner',
        required: false

      attribute :status,
        type: 'String',
        json_key: 'status',
        required: false

      attribute :trigger_condition,
        type: 'TriggerCondition',
        json_key: 'trigger_condition',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
