# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ListDashboardsResponseBodyItem
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :created,
        type: 'Time',
        json_key: 'created',
        required: true

      attribute :dashboard_id,
        type: 'String',
        json_key: 'dashboard_id',
        required: true

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: true

      attribute :folder_id,
        type: 'String',
        json_key: 'folder_id',
        required: true

      attribute :folder_name,
        type: 'String',
        json_key: 'folder_name',
        required: true

      attribute :hash,
        type: 'String',
        json_key: 'hash',
        required: true

      attribute :owner,
        type: 'String',
        json_key: 'owner',
        required: true

      attribute :role,
        type: 'String',
        json_key: 'role',
        required: true

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: true

      attribute :updated_at,
        type: 'Integer',
        json_key: 'updatedAt',
        required: true

      attribute :v1,
        type: 'Dashboard',
        json_key: 'v1',
        required: false

      attribute :v2,
        type: 'Dashboard',
        json_key: 'v2',
        required: false

      attribute :v3,
        type: 'Dashboard',
        json_key: 'v3',
        required: false

      attribute :v4,
        type: 'Dashboard',
        json_key: 'v4',
        required: false

      attribute :v5,
        type: 'Dashboard',
        json_key: 'v5',
        required: false

      attribute :v6,
        type: 'Dashboard',
        json_key: 'v6',
        required: false

      attribute :v7,
        type: 'Dashboard',
        json_key: 'v7',
        required: false

      attribute :v8,
        type: 'Dashboard',
        json_key: 'v8',
        required: false

      attribute :version,
        type: 'Integer',
        json_key: 'version',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
