# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ListDestinations200ResponseInner
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :aws_region,
        type: 'String',
        json_key: 'aws_region',
        required: false

      attribute :destination_type_name,
        type: 'String',
        json_key: 'destination_type_name',
        required: false

      attribute :emails,
        type: 'Array<String>',
        json_key: 'emails',
        required: false

      attribute :headers,
        type: 'Hash<String, String>',
        json_key: 'headers',
        required: false

      attribute :metadata,
        type: 'Hash<String, String>',
        json_key: 'metadata',
        required: false

      attribute :method,
        type: 'HTTPType',
        json_key: 'method',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :output_format,
        type: 'HTTPOutputFormat',
        json_key: 'output_format',
        required: false

      attribute :skip_tls_verify,
        type: 'Boolean',
        json_key: 'skip_tls_verify',
        required: false

      attribute :sns_topic_arn,
        type: 'String',
        json_key: 'sns_topic_arn',
        required: false

      attribute :template,
        type: 'String',
        json_key: 'template',
        required: false

      attribute :type,
        type: 'DestinationType',
        json_key: 'type',
        required: false

      attribute :url,
        type: 'String',
        json_key: 'url',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
