# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class LokiEntry
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :line,
        type: 'String',
        json_key: 'line',
        required: true

      attribute :structured_metadata,
        type: 'Hash<String, String>',
        json_key: 'structured_metadata',
        required: false

      attribute :timestamp,
        type: 'String',
        json_key: 'timestamp',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
