# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class MapView
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :lat,
        type: 'Float',
        json_key: 'lat',
        required: false

      attribute :lng,
        type: 'Float',
        json_key: 'lng',
        required: false

      attribute :zoom,
        type: 'Float',
        json_key: 'zoom',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
