# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class MapSymbolStyle
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :size,
        type: 'String',
        json_key: 'size',
        required: false

      attribute :size_by_value,
        type: 'SizeByValue',
        json_key: 'size_by_value',
        required: false

      attribute :size_fixed,
        type: 'Float',
        json_key: 'size_fixed',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
