# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Metadata
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :help,
        type: 'String',
        json_key: 'help',
        required: true

      attribute :metric_family_name,
        type: 'String',
        json_key: 'metric_family_name',
        required: true

      attribute :metric_type,
        type: 'MetricType',
        json_key: 'metric_type',
        required: true

      attribute :unit,
        type: 'String',
        json_key: 'unit',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
