# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module MetricType
      UNKNOWN = 'Unknown'
      COUNTER = 'Counter'
      GAUGE = 'Gauge'
      HISTOGRAM = 'Histogram'
      GAUGE_HISTOGRAM = 'GaugeHistogram'
      EXPONENTIAL_HISTOGRAM = 'ExponentialHistogram'
      SUMMARY = 'Summary'
      INFO = 'Info'
      STATE_SET = 'StateSet'
      EMPTY = 'Empty'

      def self.all
        @all ||= [
          UNKNOWN,
          COUNTER,
          GAUGE,
          HISTOGRAM,
          GAUGE_HISTOGRAM,
          EXPONENTIAL_HISTOGRAM,
          SUMMARY,
          INFO,
          STATE_SET,
          EMPTY,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
