# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Node
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :data,
        type: 'Object',
        json_key: 'data',
        required: true

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: true

      attribute :io_type,
        type: 'String',
        json_key: 'io_type',
        required: true

      attribute :meta,
        type: 'Hash<String, String>',
        json_key: 'meta',
        required: false

      attribute :position,
        type: 'Position',
        json_key: 'position',
        required: true

      attribute :style,
        type: 'NodeStyle',
        json_key: 'style',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
