# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module Operator
      EQUAL = '='
      EXCLAMATION_EQUAL = '!='
      GREATER_THAN = '>'
      GREATER_THAN_EQUAL = '>='
      LESS_THAN = '<'
      LESS_THAN_EQUAL = '<='
      CONTAINS = 'contains'
      NOT_CONTAINS = 'not_contains'

      def self.all
        @all ||= [
          EQUAL,
          EXCLAMATION_EQUAL,
          GREATER_THAN,
          GREATER_THAN_EQUAL,
          LESS_THAN,
          LESS_THAN_EQUAL,
          CONTAINS,
          NOT_CONTAINS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
