# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class OrgDetails
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :user_obj,
        type: 'OrgUser',
        json_key: 'UserObj',
        required: true

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: true

      attribute :identifier,
        type: 'String',
        json_key: 'identifier',
        required: true

      attribute :ingest_threshold,
        type: 'Integer',
        json_key: 'ingest_threshold',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :plan,
        type: 'Integer',
        json_key: 'plan',
        required: false

      attribute :search_threshold,
        type: 'Integer',
        json_key: 'search_threshold',
        required: true

      attribute :type,
        type: 'String',
        json_key: 'type',
        required: true

      attribute :user_email,
        type: 'String',
        json_key: 'user_email',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
