# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class OrganizationSetting
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :cross_links,
        type: 'Array<CrossLink>',
        json_key: 'cross_links',
        required: false

      attribute :dark_mode_theme_color,
        type: 'String',
        json_key: 'dark_mode_theme_color',
        required: false

      attribute :enable_streaming_search,
        type: 'Boolean',
        json_key: 'enable_streaming_search',
        required: false

      attribute :free_trial_expiry,
        type: 'Integer',
        json_key: 'free_trial_expiry',
        required: false

      attribute :light_mode_theme_color,
        type: 'String',
        json_key: 'light_mode_theme_color',
        required: false

      attribute :max_series_per_query,
        type: 'Integer',
        json_key: 'max_series_per_query',
        required: false,
        minimum: 0

      attribute :min_auto_refresh_interval,
        type: 'Integer',
        json_key: 'min_auto_refresh_interval',
        required: false,
        minimum: 0

      attribute :org_storage_enabled,
        type: 'Boolean',
        json_key: 'org_storage_enabled',
        required: false

      attribute :scrape_interval,
        type: 'Integer',
        json_key: 'scrape_interval',
        required: false,
        minimum: 0

      attribute :span_id_field_name,
        type: 'String',
        json_key: 'span_id_field_name',
        required: false

      attribute :streaming_aggregation_enabled,
        type: 'Boolean',
        json_key: 'streaming_aggregation_enabled',
        required: false

      attribute :toggle_ingestion_logs,
        type: 'Boolean',
        json_key: 'toggle_ingestion_logs',
        required: false

      attribute :trace_id_field_name,
        type: 'String',
        json_key: 'trace_id_field_name',
        required: false

      attribute :usage_stream_enabled,
        type: 'Boolean',
        json_key: 'usage_stream_enabled',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
