# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class PanelConfig
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :aggregation,
        type: 'String',
        json_key: 'aggregation',
        required: false

      attribute :axis_border_show,
        type: 'Boolean',
        json_key: 'axis_border_show',
        required: false

      attribute :axis_label_rotate,
        type: 'Float',
        json_key: 'axis_label_rotate',
        required: false

      attribute :axis_label_truncate_width,
        type: 'Float',
        json_key: 'axis_label_truncate_width',
        required: false

      attribute :axis_width,
        type: 'Float',
        json_key: 'axis_width',
        required: false

      attribute :background,
        type: 'Background',
        json_key: 'background',
        required: false

      attribute :base_map,
        type: 'BaseMap',
        json_key: 'base_map',
        required: false

      attribute :chart_align,
        type: 'String',
        json_key: 'chart_align',
        required: false

      attribute :color,
        type: 'ColorCfg',
        json_key: 'color',
        required: false

      attribute :column_order,
        type: 'Array<String>',
        json_key: 'column_order',
        required: false

      attribute :connect_nulls,
        type: 'Boolean',
        json_key: 'connect_nulls',
        required: false

      attribute :decimals,
        type: 'Float',
        json_key: 'decimals',
        required: false

      attribute :drilldown,
        type: 'Array<DrillDown>',
        json_key: 'drilldown',
        required: false

      attribute :hidden_columns,
        type: 'Array<String>',
        json_key: 'hidden_columns',
        required: false

      attribute :label_option,
        type: 'LabelOption',
        json_key: 'label_option',
        required: false

      attribute :lat_label,
        type: 'String',
        json_key: 'lat_label',
        required: false

      attribute :legend_height,
        type: 'LegendHeight',
        json_key: 'legend_height',
        required: false

      attribute :legend_width,
        type: 'LegendWidth',
        json_key: 'legend_width',
        required: false

      attribute :legends_position,
        type: 'String',
        json_key: 'legends_position',
        required: false

      attribute :legends_type,
        type: 'String',
        json_key: 'legends_type',
        required: false

      attribute :line_interpolation,
        type: 'LineInterpolation',
        json_key: 'line_interpolation',
        required: false

      attribute :line_thickness,
        type: 'Float',
        json_key: 'line_thickness',
        required: false

      attribute :lon_label,
        type: 'String',
        json_key: 'lon_label',
        required: false

      attribute :map_symbol_style,
        type: 'MapSymbolStyle',
        json_key: 'map_symbol_style',
        required: false

      attribute :map_type,
        type: 'MapType',
        json_key: 'map_type',
        required: false

      attribute :map_view,
        type: 'MapView',
        json_key: 'map_view',
        required: false

      attribute :mappings,
        type: 'Array<Mapping>',
        json_key: 'mappings',
        required: false

      attribute :mark_line,
        type: 'Array<MarkLine>',
        json_key: 'mark_line',
        required: false

      attribute :name_label,
        type: 'String',
        json_key: 'name_label',
        required: false

      attribute :no_value_replacement,
        type: 'String',
        json_key: 'no_value_replacement',
        required: false

      attribute :override_config,
        type: 'Array<OverrideConfig>',
        json_key: 'override_config',
        required: false

      attribute :panel_time_enabled,
        type: 'Boolean',
        json_key: 'panel_time_enabled',
        required: false

      attribute :panel_time_range,
        type: 'DateTimeOptions',
        json_key: 'panel_time_range',
        required: false

      attribute :promql_table_mode,
        type: 'String',
        json_key: 'promql_table_mode',
        required: false

      attribute :show_gridlines,
        type: 'Boolean',
        json_key: 'show_gridlines',
        required: false

      attribute :show_legends,
        type: 'Boolean',
        json_key: 'show_legends',
        required: true

      attribute :show_symbol,
        type: 'Boolean',
        json_key: 'show_symbol',
        required: false

      attribute :step_value,
        type: 'String',
        json_key: 'step_value',
        required: false

      attribute :sticky_columns,
        type: 'Array<String>',
        json_key: 'sticky_columns',
        required: false

      attribute :sticky_first_column,
        type: 'Boolean',
        json_key: 'sticky_first_column',
        required: false

      attribute :table_aggregations,
        type: 'Array<String>',
        json_key: 'table_aggregations',
        required: false

      attribute :table_dynamic_columns,
        type: 'Boolean',
        json_key: 'table_dynamic_columns',
        required: false

      attribute :table_pagination,
        type: 'Boolean',
        json_key: 'table_pagination',
        required: false

      attribute :table_pagination_rows_per_page,
        type: 'Integer',
        json_key: 'table_pagination_rows_per_page',
        required: false

      attribute :table_pivot_show_col_totals,
        type: 'Boolean',
        json_key: 'table_pivot_show_col_totals',
        required: false

      attribute :table_pivot_show_row_totals,
        type: 'Boolean',
        json_key: 'table_pivot_show_row_totals',
        required: false

      attribute :table_pivot_sticky_col_totals,
        type: 'Boolean',
        json_key: 'table_pivot_sticky_col_totals',
        required: false

      attribute :table_pivot_sticky_row_totals,
        type: 'Boolean',
        json_key: 'table_pivot_sticky_row_totals',
        required: false

      attribute :table_transpose,
        type: 'Boolean',
        json_key: 'table_transpose',
        required: false

      attribute :top_results,
        type: 'Float',
        json_key: 'top_results',
        required: false

      attribute :top_results_others,
        type: 'Boolean',
        json_key: 'top_results_others',
        required: false

      attribute :trellis,
        type: 'Trellis',
        json_key: 'trellis',
        required: false

      attribute :unit,
        type: 'String',
        json_key: 'unit',
        required: false

      attribute :unit_custom,
        type: 'String',
        json_key: 'unit_custom',
        required: false

      attribute :visible_columns,
        type: 'Array<String>',
        json_key: 'visible_columns',
        required: false

      attribute :weight_label,
        type: 'String',
        json_key: 'weight_label',
        required: false

      attribute :wrap_table_cells,
        type: 'Boolean',
        json_key: 'wrap_table_cells',
        required: false

      attribute :y_axis_max,
        type: 'Float',
        json_key: 'y_axis_max',
        required: false

      attribute :y_axis_min,
        type: 'Float',
        json_key: 'y_axis_min',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
