# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Panel
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :config,
        type: 'PanelConfig',
        json_key: 'config',
        required: true

      attribute :custom_chart_content,
        type: 'String',
        json_key: 'customChartContent',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: true

      attribute :html_content,
        type: 'String',
        json_key: 'htmlContent',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: true

      attribute :layout,
        type: 'Layout',
        json_key: 'layout',
        required: false

      attribute :markdown_content,
        type: 'String',
        json_key: 'markdownContent',
        required: false

      attribute :queries,
        type: 'Array<Query>',
        json_key: 'queries',
        required: true

      attribute :query_type,
        type: 'String',
        json_key: 'queryType',
        required: false

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: true

      attribute :type,
        type: 'String',
        json_key: 'type',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
