# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class PanelFields
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :breakdown,
        type: 'Array<AxisItem>',
        json_key: 'breakdown',
        required: false

      attribute :filter,
        type: 'PanelFilter',
        json_key: 'filter',
        required: true

      attribute :latitude,
        type: 'AxisItem',
        json_key: 'latitude',
        required: false

      attribute :longitude,
        type: 'AxisItem',
        json_key: 'longitude',
        required: false

      attribute :name,
        type: 'AxisItem',
        json_key: 'name',
        required: false

      attribute :promql_labels,
        type: 'Array<PromQLLabelFilter>',
        json_key: 'promql_labels',
        required: false

      attribute :promql_operations,
        type: 'Array<PromQLOperation>',
        json_key: 'promql_operations',
        required: false

      attribute :source,
        type: 'AxisItem',
        json_key: 'source',
        required: false

      attribute :stream,
        type: 'String',
        json_key: 'stream',
        required: true

      attribute :stream_type,
        type: 'StreamType',
        json_key: 'stream_type',
        required: true

      attribute :target,
        type: 'AxisItem',
        json_key: 'target',
        required: false

      attribute :value,
        type: 'AxisItem',
        json_key: 'value',
        required: false

      attribute :value_for_maps,
        type: 'AxisItem',
        json_key: 'value_for_maps',
        required: false

      attribute :weight,
        type: 'AxisItem',
        json_key: 'weight',
        required: false

      attribute :x,
        type: 'Array<AxisItem>',
        json_key: 'x',
        required: true

      attribute :y,
        type: 'Array<AxisItem>',
        json_key: 'y',
        required: true

      attribute :z,
        type: 'Array<AxisItem>',
        json_key: 'z',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
