# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class PipelineErrorInfo
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :error_summary,
        type: 'String',
        json_key: 'error_summary',
        required: false

      attribute :last_error_timestamp,
        type: 'Integer',
        json_key: 'last_error_timestamp',
        required: true

      attribute :node_errors,
        type: 'Object',
        json_key: 'node_errors',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
