# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class PipelineHistoryEntry
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :delay_in_secs,
        type: 'Integer',
        json_key: 'delay_in_secs',
        required: false

      attribute :end_time,
        type: 'Integer',
        json_key: 'end_time',
        required: true

      attribute :error,
        type: 'String',
        json_key: 'error',
        required: false

      attribute :evaluation_took_in_secs,
        type: 'Float',
        json_key: 'evaluation_took_in_secs',
        required: false

      attribute :is_partial,
        type: 'Boolean',
        json_key: 'is_partial',
        required: false

      attribute :is_realtime,
        type: 'Boolean',
        json_key: 'is_realtime',
        required: true

      attribute :is_silenced,
        type: 'Boolean',
        json_key: 'is_silenced',
        required: true

      attribute :org,
        type: 'String',
        json_key: 'org',
        required: true

      attribute :pipeline_name,
        type: 'String',
        json_key: 'pipeline_name',
        required: true

      attribute :query_took,
        type: 'Integer',
        json_key: 'query_took',
        required: false

      attribute :retries,
        type: 'Integer',
        json_key: 'retries',
        required: true

      attribute :source_node,
        type: 'String',
        json_key: 'source_node',
        required: false

      attribute :start_time,
        type: 'Integer',
        json_key: 'start_time',
        required: true

      attribute :status,
        type: 'String',
        json_key: 'status',
        required: true

      attribute :success_response,
        type: 'String',
        json_key: 'success_response',
        required: false

      attribute :timestamp,
        type: 'Integer',
        json_key: 'timestamp',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
