# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class PipelineSourceOneOf1
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :delay,
        type: 'Integer',
        json_key: 'delay',
        required: false

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: false

      attribute :query_condition,
        type: 'QueryCondition',
        json_key: 'query_condition',
        required: false

      attribute :start_at,
        type: 'Integer',
        json_key: 'start_at',
        required: false

      attribute :stream_type,
        type: 'StreamType',
        json_key: 'stream_type',
        required: false

      attribute :trigger_condition,
        type: 'TriggerCondition',
        json_key: 'trigger_condition',
        required: false

      attribute :tz_offset,
        type: 'Integer',
        json_key: 'tz_offset',
        required: false

      attribute :source_type,
        type: 'String',
        json_key: 'source_type',
        required: true,
        enum: ['scheduled']

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
