# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class PromQLOperation
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :params,
        type: 'Array<PromQLOperationParam>',
        json_key: 'params',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
