# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class QueryConfig
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :layer_type,
        type: 'String',
        json_key: 'layer_type',
        required: false

      attribute :limit,
        type: 'Float',
        json_key: 'limit',
        required: false

      attribute :max,
        type: 'Float',
        json_key: 'max',
        required: false

      attribute :min,
        type: 'Float',
        json_key: 'min',
        required: false

      attribute :promql_legend,
        type: 'String',
        json_key: 'promql_legend',
        required: true

      attribute :query_label,
        type: 'String',
        json_key: 'query_label',
        required: false

      attribute :step_value,
        type: 'String',
        json_key: 'step_value',
        required: false

      attribute :time_shift,
        type: 'Array<TimeShift>',
        json_key: 'time_shift',
        required: false

      attribute :weight_fixed,
        type: 'Float',
        json_key: 'weight_fixed',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
