# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module QueryType
      CUSTOM = 'custom'
      SQL = 'sql'
      PROMQL = 'promql'

      def self.all
        @all ||= [
          CUSTOM,
          SQL,
          PROMQL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
