# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class QueryCondition
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :aggregation,
        type: 'Aggregation',
        json_key: 'aggregation',
        required: false

      attribute :conditions,
        type: 'Object',
        json_key: 'conditions',
        required: false

      attribute :multi_time_range,
        type: 'Array<CompareHistoricData>',
        json_key: 'multi_time_range',
        required: false

      attribute :promql,
        type: 'String',
        json_key: 'promql',
        required: false

      attribute :promql_condition,
        type: 'Condition',
        json_key: 'promql_condition',
        required: false

      attribute :search_event_type,
        type: 'SearchEventType',
        json_key: 'search_event_type',
        required: false

      attribute :sql,
        type: 'String',
        json_key: 'sql',
        required: false

      attribute :type,
        type: 'QueryType',
        json_key: 'type',
        required: false

      attribute :vrl_function,
        type: 'String',
        json_key: 'vrl_function',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
