# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class QueryStatus
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :created_at,
        type: 'Integer',
        json_key: 'created_at',
        required: true

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: false

      attribute :query,
        type: 'QueryInfo',
        json_key: 'query',
        required: false

      attribute :scan_stats,
        type: 'ScanStats',
        json_key: 'scan_stats',
        required: false

      attribute :search_event_context,
        type: 'SearchEventContext',
        json_key: 'search_event_context',
        required: false

      attribute :search_type,
        type: 'SearchEventType',
        json_key: 'search_type',
        required: false

      attribute :started_at,
        type: 'Integer',
        json_key: 'started_at',
        required: true

      attribute :status,
        type: 'String',
        json_key: 'status',
        required: true

      attribute :stream_type,
        type: 'String',
        json_key: 'stream_type',
        required: false

      attribute :trace_id,
        type: 'String',
        json_key: 'trace_id',
        required: true

      attribute :user_id,
        type: 'String',
        json_key: 'user_id',
        required: false

      attribute :work_group,
        type: 'String',
        json_key: 'work_group',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
