# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class QueryData
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :field,
        type: 'String',
        json_key: 'field',
        required: false

      attribute :filter,
        type: 'Array<Filters>',
        json_key: 'filter',
        required: false

      attribute :max_record_size,
        type: 'Integer',
        json_key: 'max_record_size',
        required: false

      attribute :stream,
        type: 'String',
        json_key: 'stream',
        required: false

      attribute :stream_type,
        type: 'StreamType',
        json_key: 'stream_type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
