# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Query
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :config,
        type: 'QueryConfig',
        json_key: 'config',
        required: true

      attribute :custom_query,
        type: 'Boolean',
        json_key: 'customQuery',
        required: true

      attribute :fields,
        type: 'PanelFields',
        json_key: 'fields',
        required: true

      attribute :joins,
        type: 'Array<Join>',
        json_key: 'joins',
        required: false

      attribute :query,
        type: 'String',
        json_key: 'query',
        required: false

      attribute :tab_name,
        type: 'String',
        json_key: 'tabName',
        required: false

      attribute :vrl_function_query,
        type: 'String',
        json_key: 'vrlFunctionQuery',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
