# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class RecordStatus
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :error,
        type: 'String',
        json_key: 'error',
        required: false

      attribute :failed,
        type: 'Integer',
        json_key: 'failed',
        required: true,
        minimum: 0

      attribute :successful,
        type: 'Integer',
        json_key: 'successful',
        required: true,
        minimum: 0

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
