# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ReportTimerange
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :from,
        type: 'Integer',
        json_key: 'from',
        required: true

      attribute :period,
        type: 'String',
        json_key: 'period',
        required: true

      attribute :to,
        type: 'Integer',
        json_key: 'to',
        required: true

      attribute :type,
        type: 'ReportTimerangeType',
        json_key: 'type',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
