# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module ReportMediaType
      PDF = 'pdf'
      PNG = 'png'
      CSV = 'csv'

      def self.all
        @all ||= [
          PDF,
          PNG,
          CSV,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
