# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module ReportFrequencyType
      ONCE = 'once'
      HOURS = 'hours'
      DAYS = 'days'
      WEEKS = 'weeks'
      MONTHS = 'months'
      CRON = 'cron'

      def self.all
        @all ||= [
          ONCE,
          HOURS,
          DAYS,
          WEEKS,
          MONTHS,
          CRON,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
