# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ReportDashboard
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :attachment_dimensions,
        type: 'ReportAttachmentDimensions',
        json_key: 'attachment_dimensions',
        required: false

      attribute :dashboard,
        type: 'String',
        json_key: 'dashboard',
        required: true

      attribute :email_attachment_type,
        type: 'ReportEmailAttachmentType',
        json_key: 'email_attachment_type',
        required: false

      attribute :folder,
        type: 'String',
        json_key: 'folder',
        required: true

      attribute :report_type,
        type: 'ReportMediaType',
        json_key: 'report_type',
        required: false

      attribute :tabs,
        type: 'Array<String>',
        json_key: 'tabs',
        required: true

      attribute :timerange,
        type: 'ReportTimerange',
        json_key: 'timerange',
        required: false

      attribute :variables,
        type: 'Array<ReportDashboardVariable>',
        json_key: 'variables',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
