# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ReportFrequency
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :align_time,
        type: 'Boolean',
        json_key: 'align_time',
        required: false

      attribute :cron,
        type: 'String',
        json_key: 'cron',
        required: false

      attribute :interval,
        type: 'Integer',
        json_key: 'interval',
        required: false

      attribute :type,
        type: 'ReportFrequencyType',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
