# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module RequestEncoding
      BASE64 = 'base64'
      EMPTY = 'Empty'

      def self.all
        @all ||= [
          BASE64,
          EMPTY,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
