# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ResponseTook
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :cache_took,
        type: 'Integer',
        json_key: 'cache_took',
        required: true,
        minimum: 0

      attribute :file_list_took,
        type: 'Integer',
        json_key: 'file_list_took',
        required: true,
        minimum: 0

      attribute :idx_took,
        type: 'Integer',
        json_key: 'idx_took',
        required: true,
        minimum: 0

      attribute :search_took,
        type: 'Integer',
        json_key: 'search_took',
        required: true,
        minimum: 0

      attribute :total,
        type: 'Integer',
        json_key: 'total',
        required: true,
        minimum: 0

      attribute :wait_in_queue,
        type: 'Integer',
        json_key: 'wait_in_queue',
        required: true,
        minimum: 0

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
