# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class RumIngestionToken
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :rum_token,
        type: 'String',
        json_key: 'rum_token',
        required: false

      attribute :user,
        type: 'String',
        json_key: 'user',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
