# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ScanStats
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :aggs_cache_ratio,
        type: 'Integer',
        json_key: 'aggs_cache_ratio',
        required: true

      attribute :compressed_size,
        type: 'Integer',
        json_key: 'compressed_size',
        required: true

      attribute :file_list_took,
        type: 'Integer',
        json_key: 'file_list_took',
        required: true

      attribute :files,
        type: 'Integer',
        json_key: 'files',
        required: true

      attribute :idx_scan_size,
        type: 'Integer',
        json_key: 'idx_scan_size',
        required: true

      attribute :idx_took,
        type: 'Integer',
        json_key: 'idx_took',
        required: true

      attribute :original_size,
        type: 'Integer',
        json_key: 'original_size',
        required: true

      attribute :peak_memory_usage,
        type: 'Integer',
        json_key: 'peak_memory_usage',
        required: true

      attribute :querier_disk_cached_files,
        type: 'Integer',
        json_key: 'querier_disk_cached_files',
        required: true

      attribute :querier_files,
        type: 'Integer',
        json_key: 'querier_files',
        required: true

      attribute :querier_memory_cached_files,
        type: 'Integer',
        json_key: 'querier_memory_cached_files',
        required: true

      attribute :records,
        type: 'Integer',
        json_key: 'records',
        required: true

      attribute :wait_in_queue,
        type: 'Integer',
        json_key: 'wait_in_queue',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
