# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class SearchPartitionRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :clusters,
        type: 'Array<String>',
        json_key: 'clusters',
        required: false

      attribute :encoding,
        type: 'RequestEncoding',
        json_key: 'encoding',
        required: false

      attribute :end_time,
        type: 'Integer',
        json_key: 'end_time',
        required: true

      attribute :histogram_interval,
        type: 'Integer',
        json_key: 'histogram_interval',
        required: false

      attribute :query_fn,
        type: 'String',
        json_key: 'query_fn',
        required: false

      attribute :regions,
        type: 'Array<String>',
        json_key: 'regions',
        required: false

      attribute :sampling_ratio,
        type: 'Float',
        json_key: 'sampling_ratio',
        required: false

      attribute :search_type,
        type: 'SearchEventType',
        json_key: 'search_type',
        required: false

      attribute :sql,
        type: 'String',
        json_key: 'sql',
        required: true

      attribute :start_time,
        type: 'Integer',
        json_key: 'start_time',
        required: true

      attribute :streaming_output,
        type: 'Boolean',
        json_key: 'streaming_output',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
