# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class SearchHistoryRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :end_time,
        type: 'Integer',
        json_key: 'end_time',
        required: true

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: false

      attribute :size,
        type: 'Integer',
        json_key: 'size',
        required: false

      attribute :start_time,
        type: 'Integer',
        json_key: 'start_time',
        required: true

      attribute :stream_name,
        type: 'String',
        json_key: 'stream_name',
        required: false

      attribute :stream_type,
        type: 'String',
        json_key: 'stream_type',
        required: false

      attribute :trace_id,
        type: 'String',
        json_key: 'trace_id',
        required: false

      attribute :user_email,
        type: 'String',
        json_key: 'user_email',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
