# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class SearchSQLRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :clear_cache,
        type: 'Boolean',
        json_key: 'clear_cache',
        required: false

      attribute :clusters,
        type: 'Array<String>',
        json_key: 'clusters',
        required: false

      attribute :encoding,
        type: 'RequestEncoding',
        json_key: 'encoding',
        required: false

      attribute :local_mode,
        type: 'Boolean',
        json_key: 'local_mode',
        required: false

      attribute :query,
        type: 'SearchQuery',
        json_key: 'query',
        required: true

      attribute :regions,
        type: 'Array<String>',
        json_key: 'regions',
        required: false

      attribute :search_event_context,
        type: 'SearchEventContext',
        json_key: 'search_event_context',
        required: false

      attribute :search_type,
        type: 'SearchEventType',
        json_key: 'search_type',
        required: false

      attribute :timeout,
        type: 'Integer',
        json_key: 'timeout',
        required: false

      attribute :use_cache,
        type: 'Boolean',
        json_key: 'use_cache',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
