# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class SearchEventContext
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :alert_key,
        type: 'String',
        json_key: 'alert_key',
        required: false

      attribute :alert_name,
        type: 'String',
        json_key: 'alert_name',
        required: false

      attribute :dashboard_id,
        type: 'String',
        json_key: 'dashboard_id',
        required: false

      attribute :dashboard_name,
        type: 'String',
        json_key: 'dashboard_name',
        required: false

      attribute :derived_stream_key,
        type: 'String',
        json_key: 'derived_stream_key',
        required: false

      attribute :folder_id,
        type: 'String',
        json_key: 'folder_id',
        required: false

      attribute :folder_name,
        type: 'String',
        json_key: 'folder_name',
        required: false

      attribute :report_id,
        type: 'String',
        json_key: 'report_id',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
