# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module SearchEventType
      UI = 'ui'
      DASHBOARDS = 'dashboards'
      REPORTS = 'reports'
      ALERTS = 'alerts'
      VALUES = 'values'
      OTHER = 'other'
      RUM = 'rum'
      DERIVEDSTREAM = 'derivedstream'
      SEARCHJOB = 'searchjob'
      DOWNLOAD = 'download'
      INSIGHTS = 'insights'

      def self.all
        @all ||= [
          UI,
          DASHBOARDS,
          REPORTS,
          ALERTS,
          VALUES,
          OTHER,
          RUM,
          DERIVEDSTREAM,
          SEARCHJOB,
          DOWNLOAD,
          INSIGHTS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
