# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class SearchQuery
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :action_id,
        type: 'String',
        json_key: 'action_id',
        required: false

      attribute :end_time,
        type: 'Integer',
        json_key: 'end_time',
        required: true

      attribute :from,
        type: 'Integer',
        json_key: 'from',
        required: false

      attribute :histogram_interval,
        type: 'Integer',
        json_key: 'histogram_interval',
        required: false

      attribute :query_fn,
        type: 'String',
        json_key: 'query_fn',
        required: false

      attribute :query_type,
        type: 'String',
        json_key: 'query_type',
        required: false

      attribute :quick_mode,
        type: 'Boolean',
        json_key: 'quick_mode',
        required: false

      attribute :sampling_config,
        type: 'Object',
        json_key: 'sampling_config',
        required: false

      attribute :sampling_ratio,
        type: 'Float',
        json_key: 'sampling_ratio',
        required: false

      attribute :size,
        type: 'Integer',
        json_key: 'size',
        required: false

      attribute :skip_wal,
        type: 'Boolean',
        json_key: 'skip_wal',
        required: false

      attribute :sql,
        type: 'String',
        json_key: 'sql',
        required: true

      attribute :start_time,
        type: 'Integer',
        json_key: 'start_time',
        required: true

      attribute :streaming_id,
        type: 'String',
        json_key: 'streaming_id',
        required: false

      attribute :streaming_output,
        type: 'Boolean',
        json_key: 'streaming_output',
        required: false

      attribute :timezone,
        type: 'String',
        json_key: 'timezone',
        required: false

      attribute :track_total_hits,
        type: 'Boolean',
        json_key: 'track_total_hits',
        required: false

      attribute :uses_zo_fn,
        type: 'Boolean',
        json_key: 'uses_zo_fn',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
