# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class SearchPartitionResponse
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :compressed_size,
        type: 'Integer',
        json_key: 'compressed_size',
        required: true,
        minimum: 0

      attribute :file_num,
        type: 'Integer',
        json_key: 'file_num',
        required: true,
        minimum: 0

      attribute :histogram_interval,
        type: 'Integer',
        json_key: 'histogram_interval',
        required: false

      attribute :is_histogram_eligible,
        type: 'Boolean',
        json_key: 'is_histogram_eligible',
        required: false

      attribute :limit,
        type: 'Integer',
        json_key: 'limit',
        required: true

      attribute :max_query_range,
        type: 'Integer',
        json_key: 'max_query_range',
        required: true

      attribute :order_by,
        type: 'OrderBy',
        json_key: 'order_by',
        required: true

      attribute :original_size,
        type: 'Integer',
        json_key: 'original_size',
        required: true,
        minimum: 0

      attribute :partitions,
        type: 'Array<Array<Integer>>',
        json_key: 'partitions',
        required: true

      attribute :records,
        type: 'Integer',
        json_key: 'records',
        required: true,
        minimum: 0

      attribute :streaming_aggs,
        type: 'Boolean',
        json_key: 'streaming_aggs',
        required: true

      attribute :streaming_id,
        type: 'String',
        json_key: 'streaming_id',
        required: false

      attribute :streaming_output,
        type: 'Boolean',
        json_key: 'streaming_output',
        required: true

      attribute :trace_id,
        type: 'String',
        json_key: 'trace_id',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
