# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class SearchResponse
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :cached_ratio,
        type: 'Integer',
        json_key: 'cached_ratio',
        required: true,
        minimum: 0

      attribute :columns,
        type: 'Array<String>',
        json_key: 'columns',
        required: false

      attribute :converted_histogram_query,
        type: 'String',
        json_key: 'converted_histogram_query',
        required: false

      attribute :from,
        type: 'Integer',
        json_key: 'from',
        required: true

      attribute :function_error,
        type: 'Array<String>',
        json_key: 'function_error',
        required: false

      attribute :histogram_breakdown_field,
        type: 'String',
        json_key: 'histogram_breakdown_field',
        required: false

      attribute :histogram_interval,
        type: 'Integer',
        json_key: 'histogram_interval',
        required: false

      attribute :hits,
        type: 'Array<Object>',
        json_key: 'hits',
        required: true

      attribute :idx_scan_size,
        type: 'Integer',
        json_key: 'idx_scan_size',
        required: true,
        minimum: 0

      attribute :is_histogram_eligible,
        type: 'Boolean',
        json_key: 'is_histogram_eligible',
        required: false

      attribute :is_partial,
        type: 'Boolean',
        json_key: 'is_partial',
        required: false

      attribute :new_end_time,
        type: 'Integer',
        json_key: 'new_end_time',
        required: false

      attribute :new_start_time,
        type: 'Integer',
        json_key: 'new_start_time',
        required: false

      attribute :order_by,
        type: 'OrderBy',
        json_key: 'order_by',
        required: false

      attribute :order_by_metadata,
        type: 'Array<Array<Object>>',
        json_key: 'order_by_metadata',
        required: false

      attribute :peak_memory_usage,
        type: 'Float',
        json_key: 'peak_memory_usage',
        required: false

      attribute :query_index,
        type: 'Integer',
        json_key: 'query_index',
        required: false,
        minimum: 0

      attribute :response_type,
        type: 'String',
        json_key: 'response_type',
        required: false

      attribute :result_cache_ratio,
        type: 'Integer',
        json_key: 'result_cache_ratio',
        required: false,
        minimum: 0

      attribute :scan_records,
        type: 'Integer',
        json_key: 'scan_records',
        required: true,
        minimum: 0

      attribute :scan_size,
        type: 'Integer',
        json_key: 'scan_size',
        required: true,
        minimum: 0

      attribute :size,
        type: 'Integer',
        json_key: 'size',
        required: true

      attribute :took,
        type: 'Integer',
        json_key: 'took',
        required: true,
        minimum: 0

      attribute :took_detail,
        type: 'ResponseTook',
        json_key: 'took_detail',
        required: false

      attribute :total,
        type: 'Integer',
        json_key: 'total',
        required: true,
        minimum: 0

      attribute :trace_id,
        type: 'String',
        json_key: 'trace_id',
        required: false

      attribute :work_group,
        type: 'String',
        json_key: 'work_group',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
