# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module SendStrategy
      FIRST_WITH_COUNT = 'first_with_count'
      SUMMARY = 'summary'
      ALL = 'all'

      def self.all
        @all ||= [
          FIRST_WITH_COUNT,
          SUMMARY,
          ALL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
