# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ServiceFieldSource
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :field_name,
        type: 'String',
        json_key: 'field_name',
        required: true

      attribute :hit_count,
        type: 'Integer',
        json_key: 'hit_count',
        required: true,
        minimum: 0

      attribute :stream_types,
        type: 'Array<String>',
        json_key: 'stream_types',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
