# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class ServiceIdentityConfig
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :service_optional,
        type: 'Boolean',
        json_key: 'service_optional',
        required: false

      attribute :sets,
        type: 'Array<IdentitySet>',
        json_key: 'sets',
        required: true

      attribute :tracked_alias_ids,
        type: 'Array<String>',
        json_key: 'tracked_alias_ids',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
