# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class StreamSummary
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :num_streams,
        type: 'Integer',
        json_key: 'num_streams',
        required: true

      attribute :total_compressed_size,
        type: 'Float',
        json_key: 'total_compressed_size',
        required: true

      attribute :total_index_size,
        type: 'Float',
        json_key: 'total_index_size',
        required: true

      attribute :total_records,
        type: 'Integer',
        json_key: 'total_records',
        required: true

      attribute :total_storage_size,
        type: 'Float',
        json_key: 'total_storage_size',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
