# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class StreamStats
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :compressed_size,
        type: 'Float',
        json_key: 'compressed_size',
        required: true

      attribute :created_at,
        type: 'Integer',
        json_key: 'created_at',
        required: true

      attribute :doc_num,
        type: 'Integer',
        json_key: 'doc_num',
        required: true

      attribute :doc_time_max,
        type: 'Integer',
        json_key: 'doc_time_max',
        required: true

      attribute :doc_time_min,
        type: 'Integer',
        json_key: 'doc_time_min',
        required: true

      attribute :file_num,
        type: 'Integer',
        json_key: 'file_num',
        required: true

      attribute :index_size,
        type: 'Float',
        json_key: 'index_size',
        required: true

      attribute :storage_size,
        type: 'Float',
        json_key: 'storage_size',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
