# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Stream
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :is_derived,
        type: 'Boolean',
        json_key: 'is_derived',
        required: false

      attribute :metrics_meta,
        type: 'Metadata',
        json_key: 'metrics_meta',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :pattern_associations,
        type: 'Array<PatternAssociation>',
        json_key: 'pattern_associations',
        required: false

      attribute :schema,
        type: 'Array<StreamField>',
        json_key: 'schema',
        required: true

      attribute :settings,
        type: 'StreamSettings',
        json_key: 'settings',
        required: true

      attribute :stats,
        type: 'StreamStats',
        json_key: 'stats',
        required: true

      attribute :storage_type,
        type: 'String',
        json_key: 'storage_type',
        required: true

      attribute :stream_type,
        type: 'StreamType',
        json_key: 'stream_type',
        required: true

      attribute :total_fields,
        type: 'Integer',
        json_key: 'total_fields',
        required: true,
        minimum: 0

      attribute :uds_schema,
        type: 'Array<StreamField>',
        json_key: 'uds_schema',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
