# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class StreamSettings
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :approx_partition,
        type: 'Boolean',
        json_key: 'approx_partition',
        required: false

      attribute :bloom_filter_fields,
        type: 'Array<String>',
        json_key: 'bloom_filter_fields',
        required: false

      attribute :cross_links,
        type: 'Array<CrossLink>',
        json_key: 'cross_links',
        required: false

      attribute :data_retention,
        type: 'Integer',
        json_key: 'data_retention',
        required: false

      attribute :defined_schema_fields,
        type: 'Array<String>',
        json_key: 'defined_schema_fields',
        required: false

      attribute :distinct_value_fields,
        type: 'Array<DistinctField>',
        json_key: 'distinct_value_fields',
        required: false

      attribute :enable_distinct_fields,
        type: 'Boolean',
        json_key: 'enable_distinct_fields',
        required: false

      attribute :enable_log_patterns_extraction,
        type: 'Boolean',
        json_key: 'enable_log_patterns_extraction',
        required: false

      attribute :extended_retention_days,
        type: 'Array<TimeRange>',
        json_key: 'extended_retention_days',
        required: false

      attribute :flatten_level,
        type: 'Integer',
        json_key: 'flatten_level',
        required: false

      attribute :full_text_search_keys,
        type: 'Array<String>',
        json_key: 'full_text_search_keys',
        required: false

      attribute :index_all_values,
        type: 'Boolean',
        json_key: 'index_all_values',
        required: false

      attribute :index_fields,
        type: 'Array<String>',
        json_key: 'index_fields',
        required: false

      attribute :index_fields_updated_at,
        type: 'Hash<String, Integer>',
        json_key: 'index_fields_updated_at',
        required: false

      attribute :index_original_data,
        type: 'Boolean',
        json_key: 'index_original_data',
        required: false

      attribute :index_updated_at,
        type: 'Integer',
        json_key: 'index_updated_at',
        required: false

      attribute :is_llm_stream,
        type: 'Boolean',
        json_key: 'is_llm_stream',
        required: false

      attribute :max_query_range,
        type: 'Integer',
        json_key: 'max_query_range',
        required: false

      attribute :partition_keys,
        type: 'Array<StreamPartition>',
        json_key: 'partition_keys',
        required: false

      attribute :storage_type,
        type: 'StorageType',
        json_key: 'storage_type',
        required: false

      attribute :store_original_data,
        type: 'Boolean',
        json_key: 'store_original_data',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
