# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module StreamType
      LOGS = 'logs'
      METRICS = 'metrics'
      TRACES = 'traces'
      SERVICE_GRAPH = 'service_graph'
      ENRICHMENT_TABLES = 'enrichment_tables'
      FILE_LIST = 'file_list'
      METADATA = 'metadata'
      INDEX = 'index'

      def self.all
        @all ||= [
          LOGS,
          METRICS,
          TRACES,
          SERVICE_GRAPH,
          ENRICHMENT_TABLES,
          FILE_LIST,
          METADATA,
          INDEX,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
