# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class StreamInfo
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :filters,
        type: 'Hash<String, String>',
        json_key: 'filters',
        required: false

      attribute :stream_name,
        type: 'String',
        json_key: 'stream_name',
        required: true

      attribute :stream_type,
        type: 'StreamType',
        json_key: 'stream_type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
