# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class SystemSettingPayload
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :setting_category,
        type: 'String',
        json_key: 'setting_category',
        required: false

      attribute :setting_key,
        type: 'String',
        json_key: 'setting_key',
        required: true

      attribute :setting_value,
        type: 'Object',
        json_key: 'setting_value',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
