# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class SystemSetting
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :created_at,
        type: 'Integer',
        json_key: 'created_at',
        required: false

      attribute :created_by,
        type: 'String',
        json_key: 'created_by',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :org_id,
        type: 'String',
        json_key: 'org_id',
        required: false

      attribute :scope,
        type: 'SettingScope',
        json_key: 'scope',
        required: true

      attribute :setting_category,
        type: 'String',
        json_key: 'setting_category',
        required: false

      attribute :setting_key,
        type: 'String',
        json_key: 'setting_key',
        required: true

      attribute :setting_value,
        type: 'Object',
        json_key: 'setting_value',
        required: true

      attribute :updated_at,
        type: 'Integer',
        json_key: 'updated_at',
        required: false

      attribute :updated_by,
        type: 'String',
        json_key: 'updated_by',
        required: false

      attribute :user_id,
        type: 'String',
        json_key: 'user_id',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
