# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Template
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :body,
        type: 'String',
        json_key: 'body',
        required: false

      attribute :is_default,
        type: 'Boolean',
        json_key: 'isDefault',
        required: false

      attribute :is_prebuilt,
        type: 'Boolean',
        json_key: 'isPrebuilt',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: false

      attribute :type,
        type: 'DestinationType',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
