# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class Trellis
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :group_by_y_axis,
        type: 'Boolean',
        json_key: 'group_by_y_axis',
        required: false

      attribute :layout,
        type: 'String',
        json_key: 'layout',
        required: false

      attribute :num_of_columns,
        type: 'Integer',
        json_key: 'num_of_columns',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
