# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class TriggerCondition
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :align_time,
        type: 'Boolean',
        json_key: 'align_time',
        required: false

      attribute :cron,
        type: 'String',
        json_key: 'cron',
        required: false

      attribute :frequency,
        type: 'Integer',
        json_key: 'frequency',
        required: false

      attribute :frequency_type,
        type: 'FrequencyType',
        json_key: 'frequency_type',
        required: false

      attribute :operator,
        type: 'Operator',
        json_key: 'operator',
        required: false

      attribute :period,
        type: 'Integer',
        json_key: 'period',
        required: false

      attribute :silence,
        type: 'Integer',
        json_key: 'silence',
        required: false

      attribute :threshold,
        type: 'Integer',
        json_key: 'threshold',
        required: false

      attribute :timezone,
        type: 'String',
        json_key: 'timezone',
        required: false

      attribute :tolerance_in_secs,
        type: 'Integer',
        json_key: 'tolerance_in_secs',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
