# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class UpdateAnnotationsRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :annotation_id,
        type: 'String',
        json_key: 'annotation_id',
        required: false

      attribute :end_time,
        type: 'Integer',
        json_key: 'end_time',
        required: false

      attribute :panels,
        type: 'Array<String>',
        json_key: 'panels',
        required: false

      attribute :start_time,
        type: 'Integer',
        json_key: 'start_time',
        required: false

      attribute :tags,
        type: 'Array<String>',
        json_key: 'tags',
        required: false

      attribute :text,
        type: 'String',
        json_key: 'text',
        required: false

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
