# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class UpdatePipelineRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :edges,
        type: 'Array<Edge>',
        json_key: 'edges',
        required: true

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: false

      attribute :kind,
        type: 'PipelineKind',
        json_key: 'kind',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :nodes,
        type: 'Array<Node>',
        json_key: 'nodes',
        required: true

      attribute :org,
        type: 'String',
        json_key: 'org',
        required: false

      attribute :pipeline_id,
        type: 'String',
        json_key: 'pipeline_id',
        required: false

      attribute :source,
        type: 'PipelineSource',
        json_key: 'source',
        required: false

      attribute :version,
        type: 'Integer',
        json_key: 'version',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
