# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class UpdateGroupRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :add_roles,
        type: 'Array<String>',
        json_key: 'add_roles',
        required: false

      attribute :add_users,
        type: 'Array<String>',
        json_key: 'add_users',
        required: false

      attribute :remove_roles,
        type: 'Array<String>',
        json_key: 'remove_roles',
        required: false

      attribute :remove_users,
        type: 'Array<String>',
        json_key: 'remove_users',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
