# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class UpdateSettingsWrapperPatternAssociationAddInner
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :apply_at,
        type: 'String',
        json_key: 'apply_at',
        required: true

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: true

      attribute :field,
        type: 'String',
        json_key: 'field',
        required: true

      attribute :pattern,
        type: 'String',
        json_key: 'pattern',
        required: true

      attribute :pattern_id,
        type: 'String',
        json_key: 'pattern_id',
        required: true

      attribute :pattern_name,
        type: 'String',
        json_key: 'pattern_name',
        required: true

      attribute :policy,
        type: 'String',
        json_key: 'policy',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
