# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class UpdateAnomalyAlertFields
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :alert_enabled,
        type: 'Boolean',
        json_key: 'alert_enabled',
        required: false

      attribute :custom_sql,
        type: 'String',
        json_key: 'custom_sql',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :detection_function,
        type: 'String',
        json_key: 'detection_function',
        required: false

      attribute :detection_function_field,
        type: 'String',
        json_key: 'detection_function_field',
        required: false

      attribute :detection_window_seconds,
        type: 'Integer',
        json_key: 'detection_window_seconds',
        required: false

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: false

      attribute :filters,
        type: 'Object',
        json_key: 'filters',
        required: false

      attribute :folder_id,
        type: 'String',
        json_key: 'folder_id',
        required: false

      attribute :histogram_interval,
        type: 'String',
        json_key: 'histogram_interval',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :owner,
        type: 'String',
        json_key: 'owner',
        required: false

      attribute :percentile,
        type: 'Float',
        json_key: 'percentile',
        required: false

      attribute :query_mode,
        type: 'String',
        json_key: 'query_mode',
        required: false

      attribute :retrain_interval_days,
        type: 'Integer',
        json_key: 'retrain_interval_days',
        required: false

      attribute :schedule_interval,
        type: 'String',
        json_key: 'schedule_interval',
        required: false

      attribute :training_window_days,
        type: 'Integer',
        json_key: 'training_window_days',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
