# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class UserSaveRequest
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :custom_role,
        type: 'Array<String>',
        json_key: 'custom_role',
        required: false

      attribute :role,
        type: 'String',
        json_key: 'role',
        required: true

      attribute :email,
        type: 'String',
        json_key: 'email',
        required: true

      attribute :first_name,
        type: 'String',
        json_key: 'first_name',
        required: false

      attribute :is_external,
        type: 'Boolean',
        json_key: 'is_external',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'last_name',
        required: false

      attribute :password,
        type: 'String',
        json_key: 'password',
        required: true

      attribute :token,
        type: 'String',
        json_key: 'token',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
