# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    module UserRole
      ROOT = 'root'
      ADMIN = 'admin'
      EDITOR = 'editor'
      VIEWER = 'viewer'
      USER = 'user'
      SERVICE_ACCOUNT = 'service_account'
      SRE_AGENT = 'sre_agent'

      def self.all
        @all ||= [
          ROOT,
          ADMIN,
          EDITOR,
          VIEWER,
          USER,
          SERVICE_ACCOUNT,
          SRE_AGENT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
