# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenObserve::Api
  module Models
    class VariableList
      include OpenObserve::Api::Serializable
      include OpenObserve::Api::Validations

      attribute :custom_multi_select_value,
        type: 'Array<String>',
        json_key: 'customMultiSelectValue',
        required: false

      attribute :escape_single_quotes,
        type: 'Boolean',
        json_key: 'escapeSingleQuotes',
        required: false

      attribute :hide_on_dashboard,
        type: 'Boolean',
        json_key: 'hideOnDashboard',
        required: false

      attribute :label,
        type: 'String',
        json_key: 'label',
        required: false

      attribute :multi_select,
        type: 'Boolean',
        json_key: 'multiSelect',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :options,
        type: 'Array<CustomFieldsOption>',
        json_key: 'options',
        required: false

      attribute :panels,
        type: 'Array<String>',
        json_key: 'panels',
        required: false

      attribute :query_data,
        type: 'QueryData',
        json_key: 'query_data',
        required: false

      attribute :scope,
        type: 'String',
        json_key: 'scope',
        required: false

      attribute :select_all_value_for_multi_select,
        type: 'String',
        json_key: 'selectAllValueForMultiSelect',
        required: false

      attribute :tabs,
        type: 'Array<String>',
        json_key: 'tabs',
        required: false

      attribute :type,
        type: 'String',
        json_key: 'type',
        required: false

      attribute :value,
        type: 'String',
        json_key: 'value',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
