# frozen_string_literal: true

# openobserve
#
# The version of the OpenAPI document: 0.91.0
# Contact: hello@zinclabs.io
# Generated by OpenAPI Generator (https://openapi-generator.tech)

require 'erb'
require 'forwardable'
require 'json'
require 'time'

require 'faraday'
require 'faraday/multipart'
require 'zeitwerk'

module OpenObserve; end
module OpenObserve::Api
  class << self
    attr_reader :loader
  end

  # Nested moduleName: for_gem can't target a nested namespace, so drive Zeitwerk
  # explicitly. The parent module(s) above are pre-defined so `module OpenObserve::Api`
  # (here and in every generated file) reopens rather than raising NameError.
  @loader = Zeitwerk::Loader.new
  @loader.push_dir("#{__dir__}/openobserve-api", namespace: self)
  # version.rb defines VERSION (not a `Version` class). for_gem's GemInflector special-cases
  # this; a plain Loader doesn't, so ignore it for autoloading and require it directly to keep
  # OpenObserve::Api::VERSION available.
  @loader.ignore("#{__dir__}/openobserve-api/version.rb")
  require_relative "openobserve-api/version"
  # Model names keep their acronym casing (e.g. HTTPConfig), but Zeitwerk's default
  # inflector would expect HttpConfig from the file name. Register the exceptions so
  # autoloading resolves the real constant.
  @loader.inflector.inflect(
    "http_output_format" => "HTTPOutputFormat",
    "http_type" => "HTTPType",
    "prom_ql_label_filter" => "PromQLLabelFilter",
    "prom_ql_operation" => "PromQLOperation",
    "prom_ql_operation_param" => "PromQLOperationParam",
    "test_vrl_request" => "TestVRLRequest",
    "search_sql_request" => "SearchSQLRequest",
    "http_output_format_one_of_esbulk" => "HTTPOutputFormatOneOfEsbulk",
    "http_output_format_one_of" => "HTTPOutputFormatOneOf",
    "http_output_format_one_of1_stringseparated" => "HTTPOutputFormatOneOf1Stringseparated",
    "http_output_format_one_of1" => "HTTPOutputFormatOneOf1",
  )
  # The `api/` directory on disk is fixed regardless of the `apiNamespace` CliOption,
  # but api.mustache only nests classes under an `Api` module when the wrapper is
  # enabled (false). When it's disabled, tell Zeitwerk to collapse
  # that directory so it doesn't expect a `OpenObserve::Api::Api` namespace that the
  # generated classes never actually define.
  @loader.collapse("#{__dir__}/openobserve-api/api")
  @loader.setup

  def self.eager_load!
    @loader.eager_load
  end
end
